#!/usr/bin/env bash

FILE=${1:-src/main.cpp}

clang++ -std=c++20 -Wall -Wextra -Wpedantic -g -fno-omit-frame-pointer -fsanitize=address,undefined -Isrc "$FILE" -o app && ./app
# clang++ -std=c++20 "$FILE" -o app && ./app
